#!/bin/bash

# config parameters
install_dir=/opt/apps/SupplyChainApps/95/OOB
app_server=weblogic
deploy_dir=/opt/apps/jetty-oob-95/webapps/smcfs
isccs_install=/opt/apps/weblogic/user_projects/domains/mydomain/autodeploy/isccsdev
wsc_install=/opt/apps/weblogic_store/user_projects/domains/mydomain/autodeploy/wsc

# navigate to bin
cd ${install_dir}/bin

echo "********************************************"
echo "*            Choose option number          *"
echo "********************************************"
echo "* Resource jar tasks                       *"
echo "*[1] resource jar build                    *"
echo "*[2] stage resource jar                    *"
echo "*[3] automated resource jar deployment     *"
echo "*                                          *"
echo "* Entity jar tasks                         *"
echo "*[4] entity jar build                      *"
echo "*[5] stage entity jar                      *"
echo "*[6] automated entity jar deployment       *"
echo "*                                          *"
echo "* Full build tasks                         *"
echo "*[7] smcfs build                           *"
echo "*[8] stage smcfs                           *"
echo "*[9] automated smcfs deployment            *"
echo "*                                          *"
echo "* Internet Call Center                     *"
echo "*[a] build isccsdev                        *"
echo "*[b] stage isccsdev                        *"
echo "*[c] automated isccsdev deployment         *"
echo "*                                          *"
echo "* Web Store                                *"
echo "*[d] build wsc                             *"
echo "*[e] stage wsc                             *"
echo "*[f] automated wsc deployment              *"
echo "********************************************"
read -p "Enter option #:" answer

case $answer in
 [1]) # build resource jar
        echo ${install_dir}/bin/deployer.sh -t resourcejar
        ${install_dir}/bin/deployer.sh -t resourcejar
		;;
 [2]) # stage resource jar
        echo cp -vf ${install_dir}/jar/platform/5_0/resources.jar ${deploy_dir}/WEB-INF/lib/resources.jar
        cp -vf ${install_dir}/jar/platform/5_0/resources.jar ${deploy_dir}/WEB-INF/lib/resources.jar
		;;
 [4]) # build entity jar
        echo ${install_dir}/bin/deployer.sh -t entitydeployer
        ${install_dir}/bin/deployer.sh -t entitydeployer
		;;
 [5]) # stage entity jar
        echo cp -vf ${install_dir}/jar/platform/5_0/entities.jar ${deploy_dir}/WEB-INF/lib/entities.jar
        cp -vf ${install_dir}/jar/platform/5_0/entities.jar ${deploy_dir}/WEB-INF/lib/entities.jar
		;;
 [7]) # build ear
        echo ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=smcfs -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
        ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=smcfs -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
		;;
 [8]) # stage ear
	rm -rf ${deploy_dir}
	mkdir ${deploy_dir}
	cp -vf ${install_dir}/external_deployments/smcfs.ear ${deploy_dir}
	unzip -o ${deploy_dir}/smcfs.ear -d ${deploy_dir}/smcfs_ear
	rm -rf ${deploy_dir}/smcfs.ear
	mv -f ${deploy_dir}/smcfs_ear/smcfs.war ${deploy_dir}
	unzip -o ${deploy_dir}/smcfs.war -d ${deploy_dir}
	rm -rf ${deploy_dir}/smcfs.war
	mv -vf ${deploy_dir}/smcfs_ear/*.jar ${deploy_dir}/WEB-INF/lib/
	rm -rf ${deploy_dir}/smcfs_ear
        cp -vf /opt/apps/apache-activemq-5.14.0/activemq-all-5.14.0.jar ${deploy_dir}/WEB-INF/lib/
	;;
 [3]) # automated deploy resource jar
	echo ${install_dir}/bin/deployer.sh -t resourcejar
        ${install_dir}/bin/deployer.sh -t resourcejar
	/home/sanju/myscripts/stopall
	echo cp -vf ${install_dir}/jar/platform/5_0/resources.jar ${deploy_dir}/WEB-INF/lib/resources.jar
        cp -vf ${install_dir}/jar/platform/5_0/resources.jar ${deploy_dir}/WEB-INF/lib/resources.jar
	/home/sanju/myscripts/startall
	;;
 [6]) # automated deploy entity jar
	echo ${install_dir}/bin/deployer.sh -t entitydeployer
        ${install_dir}/bin/deployer.sh -t entitydeployer
	/home/sanju/myscripts/stopall
        echo cp -vf ${install_dir}/jar/platform/5_0/entities.jar ${deploy_dir}/WEB-INF/lib/entities.jar
        cp -vf ${install_dir}/jar/platform/5_0/entities.jar ${deploy_dir}/WEB-INF/lib/entities.jar
	/home/sanju/myscripts/startall
	;;
 [9]) # automated deploy ear
	# build
	echo ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=smcfs -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
        ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=smcfs -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
	# stop server
	/home/sanju/myscripts/stopall
	# stage
	rm -rf ${deploy_dir}
	mkdir ${deploy_dir}
	cp -vf ${install_dir}/external_deployments/smcfs.ear ${deploy_dir}
	unzip -o ${deploy_dir}/smcfs.ear -d ${deploy_dir}/smcfs_ear
	rm -rf ${deploy_dir}/smcfs.ear
	mv -f ${deploy_dir}/smcfs_ear/smcfs.war ${deploy_dir}
	unzip -o ${deploy_dir}/smcfs.war -d ${deploy_dir}
	rm -rf ${deploy_dir}/smcfs.war
	mv -vf ${deploy_dir}/smcfs_ear/*.jar ${deploy_dir}/WEB-INF/lib/
	rm -rf ${deploy_dir}/smcfs_ear
        cp -vf /opt/apps/apache-activemq-5.14.0/activemq-all-5.14.0.jar ${deploy_dir}/WEB-INF/lib/
	# start server
	/home/sanju/myscripts/startall
	;;
 [a]) # build isccsdev
        echo ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=isccsdev -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
        ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=isccsdev -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
        ;;
 [b]) # stage isccsdev
        rm -rf ${isccs_install}
        mkdir ${isccs_install}
        cp -vf ${install_dir}/external_deployments/smcfs.ear ${isccs_install}
        unzip -o ${isccs_install}/smcfs.ear -d ${isccs_install}/smcfs_ear
        rm -rf ${isccs_install}/smcfs.ear
        mv -f ${isccs_install}/smcfs_ear/isccsdev.war ${isccs_install}
        unzip -o ${isccs_install}/isccsdev.war -d ${isccs_install}
        rm -rf ${isccs_install}/isccsdev.war
        mv -vf ${isccs_install}/smcfs_ear/*.jar ${isccs_install}/WEB-INF/lib/
        rm -rf ${isccs_install}/smcfs_ear
        cp -vf /opt/apps/apache-activemq-5.14.0/activemq-all-5.14.0.jar ${isccs_install}/WEB-INF/lib/         	
        ;;
 [d]) # build wsc
        echo ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=wscdev -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
        ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=wscdev -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
        ;;
 [e]) # stage wsc
        rm -rf ${wsc_install}
        mkdir ${wsc_install}
        cp -vf ${install_dir}/external_deployments/smcfs.ear ${wsc_install}
        unzip -o ${wsc_install}/smcfs.ear -d ${wsc_install}/smcfs_ear
        rm -rf ${wsc_install}/smcfs.ear
        mv -f ${wsc_install}/smcfs_ear/wscdev.war ${wsc_install}
        unzip -o ${wsc_install}/wscdev.war -d ${wsc_install}
        rm -rf ${wsc_install}/wscdev.war
        mv -vf ${wsc_install}/smcfs_ear/*.jar ${wsc_install}/WEB-INF/lib/
        rm -rf ${wsc_install}/smcfs_ear
        cp -vf /opt/apps/apache-activemq-5.14.0/activemq-all-5.14.0.jar ${wsc_install}/WEB-INF/lib/
        ;;
 [0]) # test scripts
	/home/sanju/myscripts/stopall
	/home/sanju/myscripts/startall 
        ;;
  *) echo "***********************************************"
     echo "*    ERROR! please enter a valid option.      *"
     echo "***********************************************"
esac
