#!/bin/bash

# config parameters
install_dir=/home/sanju/SupplyChainApps/85/LOWESR7
app_server=weblogic
deploy_dir=/opt/jetty-lowes-r7/webapps/smcfs

# navigate to bin
cd ${install_dir}/bin

echo "********************************************"
echo "*            Choose option number          *"
echo "********************************************"
echo "* Resource jar tasks                       *"
echo "*[1] resource jar build                    *"
echo "*[2] stage resource jar                    *"
echo "*[3] automated resource jar deployment     *"
echo "*                                          *"
echo "* Entity jar tasks                         *"
echo "*[4] entity jar build                      *"
echo "*[5] stage entity jar                      *"
echo "*[6] automated entity jar deployment       *"
echo "*                                          *"
echo "* Full build tasks                         *"
echo "*[7] smcfs build                           *"
echo "*[8] stage smcfs                           *"
echo "*[9] automated smcfs deployment            *"
echo "********************************************"
read -p "Enter option #:" answer

case $answer in
 [1]) # build resource jar
        echo ${install_dir}/bin/deployer.sh -t resourcejar
        ${install_dir}/bin/deployer.sh -t resourcejar
		;;
 [2]) # stage resource jar
        echo cp -vf ${install_dir}/jar/platform/5_0/resources.jar ${deploy_dir}/WEB-INF/lib/resources.jar
        cp -vf ${install_dir}/jar/platform/5_0/resources.jar ${deploy_dir}/WEB-INF/lib/resources.jar
		;;
 [4]) # build entity jar
        echo ${install_dir}/bin/deployer.sh -t entitydeployer
        ${install_dir}/bin/deployer.sh -t entitydeployer
		;;
 [5]) # stage entity jar
        echo cp -vf ${install_dir}/jar/platform/5_0/entities.jar ${deploy_dir}/WEB-INF/lib/entities.jar
        cp -vf ${install_dir}/jar/platform/5_0/entities.jar ${deploy_dir}/WEB-INF/lib/entities.jar
		;;
 [7]) # build ear
        echo ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=smcfs -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
        ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=smcfs -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
		;;
 [8]) # stage ear
	rm -rf ${deploy_dir}
	mkdir ${deploy_dir}
	cp -vf ${install_dir}/external_deployments/smcfs.ear ${deploy_dir}
	unzip -o ${deploy_dir}/smcfs.ear -d ${deploy_dir}/smcfs_ear
	rm -rf ${deploy_dir}/smcfs.ear
	mv -f ${deploy_dir}/smcfs_ear/smcfs.war ${deploy_dir}
	unzip -o ${deploy_dir}/smcfs.war -d ${deploy_dir}
	rm -rf ${deploy_dir}/smcfs.war
	mv -vf ${deploy_dir}/smcfs_ear/*.jar ${deploy_dir}/WEB-INF/lib/
	rm -rf ${deploy_dir}/smcfs_ear
	;;
 [3]) # automated deploy resource jar
	echo ${install_dir}/bin/deployer.sh -t resourcejar
        ${install_dir}/bin/deployer.sh -t resourcejar
	/home/sanju/build/stopall
	echo cp -vf ${install_dir}/jar/platform/5_0/resources.jar ${deploy_dir}/WEB-INF/lib/resources.jar
        cp -vf ${install_dir}/jar/platform/5_0/resources.jar ${deploy_dir}/WEB-INF/lib/resources.jar
	/home/sanju/build/startall
	;;
 [6]) # automated deploy entity jar
	echo ${install_dir}/bin/deployer.sh -t entitydeployer
        ${install_dir}/bin/deployer.sh -t entitydeployer
	/home/sanju/build/stopall
        echo cp -vf ${install_dir}/jar/platform/5_0/entities.jar ${deploy_dir}/WEB-INF/lib/entities.jar
        cp -vf ${install_dir}/jar/platform/5_0/entities.jar ${deploy_dir}/WEB-INF/lib/entities.jar
	/home/sanju/build/startall
	;;
 [9]) # automated deploy ear
	# build
	echo ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=smcfs -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
        ${install_dir}/bin/buildear.sh -Dappserver=${app_server} -Dwarfiles=smcfs -Dearfile=smcfs.ear -Dnodocear=true -Ddevmode=true -Dnowebservice=true create-ear
	# stop server
	/home/sanju/build/stopall
	# stage
	rm -rf ${deploy_dir}
	mkdir ${deploy_dir}
	cp -vf ${install_dir}/external_deployments/smcfs.ear ${deploy_dir}
	unzip -o ${deploy_dir}/smcfs.ear -d ${deploy_dir}/smcfs_ear
	rm -rf ${deploy_dir}/smcfs.ear
	mv -f ${deploy_dir}/smcfs_ear/smcfs.war ${deploy_dir}
	unzip -o ${deploy_dir}/smcfs.war -d ${deploy_dir}
	rm -rf ${deploy_dir}/smcfs.war
	mv -vf ${deploy_dir}/smcfs_ear/*.jar ${deploy_dir}/WEB-INF/lib/
	rm -rf ${deploy_dir}/smcfs_ear
	# start server
	/home/sanju/build/startall
	;;
 [0]) # test scripts
	/home/sanju/build/stopall
	/home/sanju/build/startall 
        ;;
  *) echo "***********************************************"
     echo "*    ERROR! please enter a valid option.      *"
     echo "***********************************************"
esac
