DEFINE DBF_NAME="smcfs_95.dbf";
DEFINE USER_NAME="OOB95";
DEFINE TABLESPACE_NAME="YFS";

CREATE SMALLFILE TABLESPACE &TABLESPACE_NAME DATAFILE '/u01/app/oracle/oradata/orcl/&DBF_NAME' SIZE 100M AUTOEXTEND ON NEXT 10K MAXSIZE UNLIMITED NOLOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER &USER_NAME PROFILE "DEFAULT" IDENTIFIED BY Sterling12 DEFAULT TABLESPACE &TABLESPACE_NAME TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

GRANT "CONNECT" TO &USER_NAME;

GRANT "DBA" TO &USER_NAME;

GRANT "RESOURCE" TO &USER_NAME;

exit;
